// Generated by nitro
import type { Serialize, Simplify } from 'nitropack'
declare module 'nitropack' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/**:trpc': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/[...trpc]').default>>>>
    }
    '/api/openapi.json': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/openapi.json').default>>>>
    }
    '/api/trpc/:trpc': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/trpc/[trpc]').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
  }
}
export {}